version: '3'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
      - image-processing
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/fastapi_db
    networks:
      - app-network

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_db
    ports:
      - "5433:5433" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  image-processing:
    build: 
      context: ./image_processor
      dockerfile: Dockerfile_image
    container_name: image_processing
    ports:
      - "8001:8000"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge